post rebase fixes

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -38,35 +38,38 @@ jobs:
       - run: ln -s $(which gfortran-14) /usr/local/bin/gfortran
         if: matrix.os == 'macos-latest'
 
-      - name: Pre-commit checks
-        if: matrix.os == 'ubuntu-latest'
-        run: |
-          pip install pre-commit
-          pre-commit run --all-files
+      # EFTCAMB MOD START
+      # disable format checks
+      # - name: Pre-commit checks
+      #   if: matrix.os == 'ubuntu-latest'
+      #   run: |
+      #     pip install pre-commit
+      #     pre-commit run --all-files
 
-      - name: Format Help Message
-        if: failure() && matrix.os == 'ubuntu-latest'
-        run: |
-          echo "❌ Code formatting or style issues detected!"
-          echo ""
-          echo "Install pre-commit hooks to auto-format on commit:"
-          echo "  pip install -e .[dev]"
-          echo "  pre-commit install"
-          echo ""
-          echo "See the errors above for details."
-          exit 1
+      # - name: Format Help Message
+      #   if: failure() && matrix.os == 'ubuntu-latest'
+      #   run: |
+      #     echo "❌ Code formatting or style issues detected!"
+      #     echo ""
+      #     echo "Install pre-commit hooks to auto-format on commit:"
+      #     echo "  pip install -e .[dev]"
+      #     echo "  pre-commit install"
+      #     echo ""
+      #     echo "See the errors above for details."
+      #     exit 1
+      # EFTCAMB MOD END
 
-    # EFTCAMB MOD START
-    # add additional EFTCAMB dependencies
-    - name: Install dependencies
-      run: |
-        python --version
-        gfortran --version
-        gcc --version
-        sudo apt-get update
-        sudo apt-get install -y libblas-dev liblapack-dev
-        pip install -e .
-    # EFTCAMB MOD END
+      # EFTCAMB MOD START
+      # add additional EFTCAMB dependencies
+      - name: Install dependencies
+        run: |
+          python --version
+          gfortran --version
+          gcc --version
+          sudo apt-get update
+          sudo apt-get install -y libblas-dev liblapack-dev
+          pip install -e .
+      # EFTCAMB MOD END
 
       - name: Run tests
         run: |
